# Generated by Django 3.0.3 on 2020-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[(1, 'خرج کرد'), (2, 'درآمد')], max_length=10, verbose_name='نوع')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='تعداد')),
                ('unit_price', models.IntegerField(verbose_name='مبلغ واحد')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
