# Generated by Django 3.0.3 on 2020-02-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name': 'ثبت دخل و خرج', 'verbose_name_plural': 'ثبت دخل و خرج'},
        ),
        migrations.AlterField(
            model_name='recording',
            name='types',
            field=models.CharField(choices=[('1', 'خرج کرد'), ('2', 'درآمد')], max_length=10, verbose_name='نوع'),
        ),
    ]
