# Generated by Django 3.0.3 on 2020-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20200216_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='total_price',
            field=models.BigIntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='unit_price',
            field=models.BigIntegerField(verbose_name='مبلغ واحد'),
        ),
    ]
