# Generated by Django 3.0.3 on 2020-02-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_auto_20200223_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='total_price',
        ),
    ]
